'use strict';

var pic = angular.module('ngPicker', []);

var datePickerTemplate = [ // Template for the date picker, no CSS, pure HTML. The date-picker tag will be replaced by this
     '<div ng-switch on="style">',
       '<div ng-switch-when="1"  class="picker-row">',
         '<div class="datePicker">',
            //'<label ng-click="selectDate()">',
            //   ' <input type="text" ng-model="currentDateObj.date" disabled>',
            //'</label>',
           '<div  class="dp-box" ng-show="selecting">',
               '<div ng-switch on="YearIAndMonthSwith">',
                        '<div class="navigation">',
                           
                            '<span class="dp-nav-item" ng-click="prev()"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>',
                            '<span class="dp-nav-item dp-navitemtext" ng-click="setYearIAndMonth(\'month\')" >{{displayDate[1]}}</span>',
                            '<span class="dp-nav-item" ng-click="next()"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>',
                            '<span class="dp-nav-item" ng-click="prevYear()"><i class="fa fa-angle-double-left" aria-hidden="true"></i></span>',
                            '<span class="dp-nav-item dp-navitemtext" ng-click="setYearIAndMonth(\'years\')" >{{displayDate[3]}}</span>',
                            '<span class="dp-nav-item" ng-click="nextYear()"><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>',
                        '</div>',
                   '<div ng-switch-default>',
                        '<span  class="dp-select-dofw" ng-repeat="day in days" ng-bind="day"></span>',
                   '<div ng-repeat="week in weeks">',
                        '<span class="dp-select-dweek"  ng-repeat="d in week" ng-click="selectDay(d)" ng-class="{active: d.selected, otherMonth: d.notCurrentMonth}">{{ d.day | date: &#39;d&#39;}}</span>',
                   '</div>',
                   '</div>',
                   '<div class="dp-y-box" ng-switch-when="years">',
                        '<span  class="dp-select-y"  ng-repeat="y in years" ng-click="setYear(y)" ng-class="{active: d.selected, otherMonth: d.notCurrentMonth}">{{ y}}</span>',
                   '</div>',
                    '<div ng-switch-when="month">',
                        '<span class="dp-select-m"  ng-repeat="m in months" ng-click="setMonth(m)" ng-class="{active: d.selected, otherMonth: d.notCurrentMonth}">{{ m}}</span>',
                   '</div>',
               '</div>',
            '</div>',
       '</div>',
        '<i ng-click="selectDate()" class="fa fa-calendar calendar-ico"></i>' ,
        '<span class="dp-inputbox">',
           '<input class="dp-input date-input" type="text" maxlength=2  placeholder="{{currentDateObj.day}}" ng-model="currentDateObj.day" ng-change="setDayAuto(currentDateObj.day)">',
           '<i ng-click="showDays()" class="fa fa-angle-down input-caret"></i>',
           '<div  class="dp-selectwrapper-d">' ,
                '<div class="dp-select-day" ng-repeat="d in dayInMonth track by $index" ng-model="currentDateObj.day" ng-click="setDay(d)" >{{ d }}</div>',
           '</div>',
        '</span>', 
        '<span class="dp-inputbox">',
          '<input class="dp-input mounth-input" type="text" maxlength=2 placeholder="{{currentDateObj.month}}" ng-model="currentDateObj.month" ng-change="setMonthAuto(currentDateObj.month)">',
           '<i ng-click="showMonth()" class="fa fa-angle-down input-caret"></i>',
           '<div ng-if="monthShow" class="dp-selectwrapper-m">',
                '<div class="dp-select-m"  ng-repeat="m in months" ng-click="setMonth(m)">{{ m}}</div>',
            '</div>',
        '</span>', 
         '<span class="dp-inputbox">',
           '<input class="dp-input year-input" type="text" maxlength=4 placeholder="{{currentDateObj.year}}" ng-model="currentDateObj.year" ng-change="setYearAuto(currentDateObj.year)">',
           '<i ng-click="showYear()" class="fa fa-angle-down input-caret"></i>',
           '<div ng-if="yearsShow" class="dp-selectwrapper-y">',
                '<div class="dp-select-y"  ng-repeat="y in years" ng-click="setYear(y)">{{ y}}</div>',
           '</div>',
        '</span>' ,
    '</div>'   ,   


     '<div ng-switch-when="2">',
     '<h1>style 2</h1>',
         '<div class="datePicker">',
            '<label ng-click="selectDate()">',
               ' <input type="text" ng-model="currentDateObj.date" disabled>',
            '</label>',
           '<div ng-show="selecting">',
               '<table ng-switch on="YearIAndMonthSwith">',
                   '<thead>',
                        '<tr>',     
                        '</tr>',
                        '<tr class="navigation">',
                           '<td ng-click="prevYear()">&lt;&lt;</td>',
                           '<td ng-click="prev()">&lt;</td>',
                           '<td class="currentDate" colspan="7" ng-click="setYearIAndMonth(\'month\')" >{{displayDate[1]}}</td>',
                           '<td class="currentDate" colspan="7" ng-click="setYearIAndMonth(\'years\')" >{{displayDate[3]}}</td>',
                           '<td ng-click="next()">&gt;</td>',
                           '<td ng-click="nextYear()">&gt;&gt;</td>',
                        '</tr>',
                    '</thead>',
                   '<tbody ng-switch-default>',
                        '<tr>',
                            '<td  ng-repeat="day in days" ng-bind="day"></td>',
                        '</tr>',
                   '<tr ng-repeat="week in weeks" class="week">',
                        '<td  ng-repeat="d in week" ng-click="selectDay(d)" ng-class="{active: d.selected, otherMonth: d.notCurrentMonth}">{{ d.day | date: &#39;d&#39;}}</td>',
                   '</tr>',
                   '</tbody>',
                   '<tbody ng-switch-when="years">',
                   '<tr  class="week">',
                        '<td  ng-repeat="y in years" ng-click="setYear(y)" ng-class="{active: d.selected, otherMonth: d.notCurrentMonth}">{{ y}}</td>',
                   '</tr>',
                   '</tbody>',
                    '<tbody ng-switch-when="month">',
                   '<tr  class="week">',
                        '<td  ng-repeat="m in months" ng-click="setMonth(m)" ng-class="{active: d.selected, otherMonth: d.notCurrentMonth}">{{ m}}</td>',
                   '</tr>',
                   '</tbody>',
               '</table>',
            '</div>',
       '</div>',
        '<div>',
           '<input type="text" maxlength=2  placeholder="{{currentDateObj.day}}" ng-model="currentDateObj.day" ng-change="setDayAuto(currentDateObj.day)">',
           '<button ng-click="showDays()">Down</button>',
           '<h3 ng-repeat="d in dayInMonth track by $index" ng-model="currentDateObj.day" ng-click="setDay(d)" >{{ d }}</h3>',
        '</div>', 
        '<div >',
          '<input type="text" maxlength=2 placeholder="{{currentDateObj.month}}" ng-model="currentDateObj.month" ng-change="setMonthAuto(currentDateObj.month)">',
           '<button ng-click="showMonth()">Down</button>',
           '<h3 ng-if="monthShow" ng-repeat="m in months" ng-click="setMonth(m)">{{ m}}</h3>',
        '</div>', 
         '<div>',
           '<input type="text" maxlength=4 placeholder="{{currentDateObj.year}}" ng-model="currentDateObj.year" ng-change="setYearAuto(currentDateObj.year)">',
           '<button ng-click="showYear()">Down</button>',
           '<h3 ng-if="yearsShow" ng-repeat="y in years" ng-click="setYear(y)">{{ y}}</h3>',
        '</div>' ,
    '</div>'   ,   
 '</div>'     
].join('\n');

pic.run([
    '$templateCache',
    function($templateCache) {
        $templateCache.put('datePicker.tmpl', datePickerTemplate); // This saves the html template we declared before in the $templateCache
    }
]);

